class_name EventBus
extends Node

signal phase_changed(phase: int)
signal bid_placed(actor_id: StringName, amount: int)
signal actor_passed(actor_id: StringName)
signal auction_won(actor_id: StringName, card_id: StringName, amount: int)
signal card_acquired(actor_id: StringName, card_id: StringName)
signal card_effect_triggered(card_id: StringName, effect_type: int, target_ids: Array[StringName])
signal card_consumed(card_id: StringName, owner_id: StringName)
signal damage_applied(actor_id: StringName, amount: int, source_card_id: StringName)
signal gold_changed(actor_id: StringName, delta: int, new_total: int, source_card_id: StringName)
signal actor_died(actor_id: StringName)
signal round_started(round_number: int, card_id: StringName)
signal round_finished(round_number: int)
signal run_finished(victory: bool, reason: String)
signal debug_logged(message: String)
signal knowledge_changed(actor_id: StringName, card_instance_id: StringName)
signal information_tokens_changed(remaining: int)
signal npc_evaluation_ready(actor_id: StringName, breakdown: Dictionary)
signal npc_dialogue_spoken(actor_id: StringName, text: String, category: StringName)
signal post_auction_started(instance_id: StringName, owner_id: StringName)
signal post_auction_completed(instance_id: StringName, action: StringName)
signal seal_open_requested(instance_id: StringName, seal_number: int)
signal seal_opened(instance_id: StringName, seal_number: int, reveal_text: String)
signal seal_accident_triggered(instance_id: StringName, seal_number: int, result_text: String)
signal card_opened(instance_id: StringName, owner_id: StringName)
signal card_kept(instance_id: StringName, owner_id: StringName)
signal sale_proposed(instance_id: StringName, buyer_id: StringName, price: int)
signal sale_accepted(instance_id: StringName, buyer_id: StringName, price: int)
signal sale_rejected(instance_id: StringName, buyer_id: StringName, price: int)
signal card_transferred(instance_id: StringName, from_id: StringName, to_id: StringName)
signal card_burned(instance_id: StringName, former_owner_id: StringName)
signal inventory_limit_reached(actor_id: StringName)
signal card_owner_changed(instance_id: StringName, owner_id: StringName)
signal negotiation_started(round_number: int)
signal negotiation_finished(round_number: int)
signal offer_created(offer_id: StringName, issuer_id: StringName, offer_type: int)
signal offer_countered(offer_id: StringName, amount: int)
signal offer_accepted(offer_id: StringName, issuer_id: StringName)
signal offer_rejected(offer_id: StringName, issuer_id: StringName)
signal relationship_changed(actor_id: StringName, value: int)
signal emotion_changed(actor_id: StringName, emotion: int)
signal tell_triggered(actor_id: StringName, tell_id: StringName, text: String)
signal secret_goal_progressed(actor_id: StringName, goal_id: StringName, progress: int)
signal emergency_ability_used(actor_id: StringName, ability_id: StringName)
signal state_updated

func log_debug(message: String) -> void:
	debug_logged.emit(message)
